services:
    example:
        build:
            dockerfile: Dockerfile
            context: .
        command: uvicorn cars_api:app --reload
        ports:
            - '4567:4567'
    
    postgres:
        image: postgres:11.4-alpine
        environment:
            POSTGRES_DB: Cars
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test
        ports:
            - '5432:5432'
        volumes:
            - ./.build/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
