services:
    example:
        build:
            dockerfile: Dockerfile
            context: .
        command: flask run --port=4567 --host=0.0.0.0
        ports:
            - '4567:4567'
    
    postgres:
        image: postgres:11.4-alpine
        environment:
            POSTGRES_DB: my_db
            POSTGRES_USER: superuser
            POSTGRES_PASSWORD: pwd
        ports:
            - '5432:5432'
        volumes:
            - ./.build/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
